trigger: none

resources:
  pipelines:
  - pipeline: ci
    source: CI
    trigger:
      branches:
        include:
          - develop

pool:
  vmImage: ubuntu-latest

stages:
- stage: Deploy_Dev
  displayName: Deploy to Development

  jobs:
  - deployment: DeployWebApp

    displayName: Deploy Web Application

    environment: Development

    strategy:
      runOnce:
        deploy:
          steps:

          - download: ci
            artifact: drop

          - task: AzureWebApp@1
            inputs:
              azureSubscription: '45138fee-3b39-4bda-bba3-d5461fad16ab'
              appType: webApp
              appName: 'Staging101'
              package: ''$(System.DefaultWorkingDirectory)/Develop Branch/drop/s.zip'
